In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.isnull().mean()*100

age           0.0
gender        0.0
fever        10.0
cough         0.0
city          0.0
has_covid     0.0
dtype: float64

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

## Column Transformer 
* ColumnTransformer applies different preprocessing methods to different columns.
* It is used when a dataset contains mixed data types (numerical and categorical).

In [7]:
from sklearn.compose import ColumnTransformer

In [8]:
transformer = ColumnTransformer(transformers=[
    ('trf1', SimpleImputer(),['fever']),
    ('trf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('trf3', OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough') # remainder--> keeps columns that are not transformed

In [9]:
trf = transformer.fit_transform(X_train)

In [10]:

transformer.transform(X_test).shape

(20, 7)

In [11]:
X_train

    age  gender  fever   cough       city
56   71    Male    NaN  Strong    Kolkata
35   82  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
17   40  Female   98.0  Strong      Delhi
94   79    Male    NaN  Strong    Kolkata
..  ...     ...    ...     ...        ...
26   19  Female  100.0    Mild    Kolkata
37   55    Male  100.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
14   51    Male  104.0    Mild  Bangalore
38   49  Female  101.0    Mild      Delhi

[80 rows x 5 columns]

In [12]:
X_train.sample(5)

    age  gender  fever   cough       city
4    65  Female  101.0    Mild     Mumbai
97   20  Female  101.0    Mild  Bangalore
17   40  Female   98.0  Strong      Delhi
7    20  Female    NaN  Strong     Mumbai
48   66    Male   99.0  Strong  Bangalore

In [13]:
df = pd.read_csv('test.csv')

In [82]:
df = pd.read_csv('test.csv', header=1)

In [83]:
df.head()

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [84]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['target']), df['target'], test_size=0.1,random_state=42)

In [86]:
x_train

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52